### ISSUE TITLE
Checklist before publishing

### ISSUE THREAD

**Issue by MikeTrizna** [SmithsonianWorkshops/2021-07-30-intro-ai-pilot#1]
Things to fix from the template:

- [x] Add an Intended Audience section (to include in the announcement email, as well)
- [x] Pull out any software requirements
- [x] Create surveys, and include links
- [ ] Come up with a Schedule (with links to the relevant section of the material)
- [x] Decide on a way to register, and link to that

**Comment by MikeTrizna** [comment]
Checked off first two with https://github.com/SmithsonianWorkshops/2021-07-30-intro-ai-pilot/commit/eba4fcc90fe1c1c3580ef29bc476c64d1927c60b

**Comment by MikeTrizna** [comment]
Created a Microsoft Form for registration, and embedded it with https://github.com/SmithsonianWorkshops/2021-07-30-intro-ai-pilot/commit/f5b393fabafe08ffd420e454d58341f19fd7e185.

**Comment by MikeTrizna** [comment]
Removed the survey section, for now (https://github.com/SmithsonianWorkshops/2021-07-30-intro-ai-pilot/commit/ddfbb4d56034c13b3b1f095b048a03108d5ee462)
